FROM golang:1.22-alpine

WORKDIR /app

RUN apk add --no-cache git ca-certificates curl

ENV PORT=8080
ENV HOST=0.0.0.0
ENV DATA_DIR=/data
ENV MEDIA_DIR=/media
ENV WEB_DIR=/app/web

RUN mkdir -p /data /media /app/web

COPY go.mod ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["go", "run", "./cmd/server/main.go"]
